# Generated by Django 2.2.3 on 2019-07-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gifticon',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lowerlimit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='originalprice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pitem',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productimg_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='product',
            name='pbrand',
            field=models.CharField(max_length=20),
        ),
    ]
