# Generated by Django 2.2.3 on 2019-07-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_product_pitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lowerlimit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='originalprice',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='productimg_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
