# Generated by Django 2.2.3 on 2019-07-25 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190725_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='lowerlimit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='originalprice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pub_date',
        ),
    ]
