# Generated by Django 2.2.3 on 2019-07-25 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_product_productimg_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Pitem',
            new_name='pitem',
        ),
    ]
