# Generated by Django 2.2.3 on 2019-07-26 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_product_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
