# Generated by Django 2.2.3 on 2019-07-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='fullname',
        ),
        migrations.AddField(
            model_name='category',
            name='originalprice',
            field=models.IntegerField(null=True),
        ),
    ]
