# Generated by Django 2.2.3 on 2019-07-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20190726_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='brand_for_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_option_for_category', models.CharField(max_length=20)),
            ],
        ),
    ]
