# Generated by Django 2.2.3 on 2019-07-27 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_brand_for_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand_for_category',
            old_name='brand_option_for_category',
            new_name='brandname',
        ),
    ]
