# Generated by Django 2.2.3 on 2019-07-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='product_id',
            field=models.IntegerField(null=True),
        ),
    ]
