# Generated by Django 2.2.3 on 2019-07-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20190725_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='published date'),
        ),
    ]
