# Generated by Django 2.2.3 on 2019-07-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20190725_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfilemodel',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='uploadfilemodel',
            name='lowerlimit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='uploadfilemodel',
            name='originalprice',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='uploadfilemodel',
            name='pbrand',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uploadfilemodel',
            name='pitem',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uploadfilemodel',
            name='productimg_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
