# Generated by Django 2.2.3 on 2019-07-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_remove_uploadfilemodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='productimg',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
