# Generated by Django 2.2.1 on 2019-08-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_uploadfilemodel_productimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
